### ISSUE TITLE
`refresh` arg in `server_list()` has inverted behavior

### ISSUE THREAD

**Issue by pablobm** [openminds/ruby-mollom#1]
`server_list` is expected to force refresh if the argument is true. However, it does it when the argument is false, due to a bad if clause.

The related `test_server_list_force_reload` doesn't need to change because it was wrong too, but becomes valid when fixing the code. The first call to `server_list` results in a refresh, the second doesn't as it is cached. The third call forces refresh, bringing the total to 2, as specified in the expectation.

The patch is this simple:

```
--- a/lib/mollom.rb
+++ b/lib/mollom.rb
@@ -137,7 +137,7 @@ class Mollom
   #  mollom.server_list
   #  # => [{:proto=>"http", :host=>"88.151.243.81"}, {:proto=>"http", :host=>"82.103.131.136"}]
   def server_list refresh = false
-    return @server_list if @server_list && refresh
+    return @server_list if @server_list && ! refresh
     STATIC_SERVER_LIST.each do |static_server|
       @server_list = get_server_list_from(static_server)
       return @server_list if @server_list
```

**Comment by DefV** [comment]
Thanks, update pushed
