### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by sun** [openminds/ruby-mollom#3]
Aloha! :)

There's a new Ruby/Rails gem https://github.com/hernan/rest_mollom, which integrates with Mollom's REST API http://mollom.com/api -- are you aware of that?

It's partially based on the code of this XML-RPC library.  Would you be interested in merging that new library into this one and joining efforts? :)

Thanks,
sun / Mollom

**Comment by hannesfostie** [comment]
Hey

Sorry for not getting back to you sooner, your email sort of got burried and I only just stumbled upon it again.

We are currently not really maintaining this, so I'm not sure if there is any use in actually merging the repositories or anything like that. We'd be happy to link to the other gem though and provide a notice on the GitHub page if that works for you?
